apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-backend
  labels:
    name: cluster-backend
    app: akka-sample-cluster
spec:
  replicas: 3
  template:
    metadata:
      name: cluster-backend
      labels:
        name: node
    spec:
      containers:
      - name: cluster-backend
        image: gcr.io/affable-skill-147422/akka-sample-cluster-backend
        command: ["/bin/sh","-c"]
        args: ["java -jar akka-sample-backend.jar 2551"]
        ports:
        - name: cluster-port
          containerPort: 2551
        env:
          - name: AKKA_SEED_DISCOVERY_SERVICE
            value: discovery-svc.default.svc.cluster.local
          - name: AKKA_THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: AKKA_SEED_PORT
            value: "2551"
