apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-backend-seed
  labels:
    name: cluster-backend-seed
    app: akka-sample-cluster
spec:
  replicas: 2
  template:
    metadata:
      name: cluster-backend-seed
      labels:
        name: seed-node
    spec:
      containers:
      - name: cluster-backend-seed
        image: gcr.io/test1-1384/akka-sample-cluster-backend
        command: ["/bin/sh","-c"]
        args: ["java -jar akka-sample-backend.jar 2551"]
        ports:
        - name: cluster-port
          containerPort: 2551
        env:
          - name: SEED_DISCOVERY_SERVICE
            value: discovery-svc.default.svc.cluster.local
          - name: THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SEED_PORT
            value: "2551"
