apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-frontend
  labels:
    name: cluster-frontend
    app: akka-sample-cluster
spec:
  replicas: 1
  template:
    metadata:
          name: cluster-frontend
          labels:
            name: frontend-node
    spec:
      containers:
      - name: cluster-frontend
        image: gcr.io/affable-skill-147422/akka-sample-cluster-frontend
        command: ["/bin/sh","-c"]
        args: ["java -jar akka-sample-frontend.jar 50 true"]
        env:
          - name: AKKA_SEED_DISCOVERY_SERVICE
            value: discovery-svc.default.svc.cluster.local
          - name: AKKA_THIS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: AKKA_SEED_PORT
            value: "2551"
